// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseList: typeof import('./components/List/lazyList/src/BaseList.vue')['default']
    BeforeOptimized: typeof import('./components/List/virtualList/beforeOptimized.vue')['default']
    copy: typeof import('./components/List/virtualList/index copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('./components/Icon/src/ElIcon.vue')['default']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    EpIcon: typeof import('./components/Icon/src/EpIcon.vue')['default']
    FixedHeight: typeof import('./components/List/virtualList/fixedHeight.vue')['default']
    HeightFixed: typeof import('./components/List/virtualList/src/HeightFixed.vue')['default']
    HeightFixedList: typeof import('./components/List/virtualList/src/heightFixedList.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HieghtFixedList: typeof import('./components/List/virtualList/src/hieghtFixedList.vue')['default']
    Icon: typeof import('./components/Icon/src/Icon.vue')['default']
    Index: typeof import('./components/List/virtualList/src/Index.vue')['default']
    Index_beforeOptimized: typeof import('./components/List/virtualList/src/index_beforeOptimized.vue')['default']
    Item: typeof import('./components/List/lazyList/item.vue')['default']
    LazyList: typeof import('./components/List/lazyList/index.vue')['default']
    List_fixedHeight: typeof import('./components/List/virtualList/src/list_fixedHeight.vue')['default']
    Optimized: typeof import('./components/List/virtualList/optimized.vue')['default']
    OptimizedList: typeof import('./components/List/lazyList/optimizedList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Src: typeof import('./components/List/virtualList/src/index.vue')['default']
    SvgIcon: typeof import('./components/Icon/src/SvgIcon.vue')['default']
    Test: typeof import('./components/List/virtualList/test.vue')['default']
    VirtualList: typeof import('./components/List/virtualList/index.vue')['default']
  }
}
