// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('./components/Icon/src/ElIcon.vue')['default']
    EpIcon: typeof import('./components/Icon/src/EpIcon.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Icon: typeof import('./components/Icon/src/Icon.vue')['default']
    SvgIcon: typeof import('./components/Icon/src/SvgIcon.vue')['default']
  }
}
